
angular.module('app', ['ngTouch', 'ngRoute', 'ngResource', 'ngCookies', 'smart-table', 'ngDialog', 'ngAnimate', 'ngSanitize', 'rt.select2', 'treeGrid', 'angucomplete-alt', 'ui.bootstrap', 'dndLists', 'ngIdle'],
function ($routeProvider, $compileProvider) {

    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|file|ftp|blob):|data:image\//);
    $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|javascript):/);
    $routeProvider.when('/', {
        templateUrl: '/Security/Index'
    }).when('/PersonnelInfoList', {
        templateUrl: '/HRM/PersonnelInfo/PersonnelInfoList#!/'
    }).when('/PersonnelInfoCreate', {
        templateUrl: '/HRM/PersonnelInfo/PersonnelInfoCreate#!/'
    }).when('/EmploymentHistoryList', {
        templateUrl: '/HRM/EmploymentHistory/EmploymentHistoryList#!/'
    }).when('/EmploymentHistoryCreate', {
        templateUrl: '/HRM/EmploymentHistory/EmploymentHistoryCreate#!/'
    }).when('/DepartmentList', {
        templateUrl: '/HRM/Department/DepartmentList#!/'
    }).when('/DepartmentCreate', {
        templateUrl: '/HRM/Department/DepartmentCreate#!/'
    }).when('/SectionList', {
        templateUrl: '/HRM/Section/SectionList#!/'
    }).when('/SectionCreate', {
        templateUrl: '/HRM/Section/SectionCreate#!/'
    }).when('/EmployeeTypeLIst', {
        templateUrl: '/HRM/EmployeeType/EmployeeTypeLIst#!/'
    }).when('/EmployeeTypeCreate', {
        templateUrl: '/HRM/EmployeeType/EmployeeTypeCreate#!/'
    }).when('/ExamList', {
        templateUrl: '/HRM/Exam/ExamList#!/'
    }).when('/ExamCreate', {
        templateUrl: '/HRM/Exam/ExamCreate#!/'
    }).when('/GradeList', {
        templateUrl: '/HRM/Grade/GradeList#!/'
    }).when('/GradeCreate', {
        templateUrl: '/HRM/Grade/GradeCreate#!/'
    }).when('/PositionList', {
        templateUrl: '/HRM/Position/PositionList#!/'
    }).when('/PositionCreate', {
        templateUrl: '/HRM/Position/PositionCreate#!/'
    }).when('/AttachmentList', {
        templateUrl: '/HRM/Attachment/AttachmentList#!/'
    }).when('/AttachmentCreate', {
        templateUrl: '/HRM/Attachment/AttachmentCreate#!/'
    }).when('/CompanyList', {
        templateUrl: '/HRM/Company/CompanyList#!/'
    }).when('/CreateCompany', {
        templateUrl: '/HRM/Company/CreateCompany#!/'
    }).when('/ShiftCreate', {
        templateUrl: '/HRM/Shift/ShiftCreate#!/'
    }).when('/ShiftList', {
        templateUrl: '/HRM/Shift/ShiftList#!/'
    }).when('/CompanyBranchList', {
        templateUrl: '/HRM/CompanyBranch/CompanyBranchList#!/'
    }).when('/CreateCompanyBranch', {
        templateUrl: '/HRM/CompanyBranch/CreateCompanyBranch#!/'
    }).when('/CreateLeavePolicy', {
        templateUrl: '/Leave/LeavePolicy/CreateLeavePolicy#!/'
    }).when('/PurchaseRequisitionList', {// Inventory
        templateUrl: '/Inventory/PurchaseRequisition/PurchaseRequisitionList#!/'
    }).when('/PurchaseRequisitionCreate', {
        templateUrl: '/Inventory/PurchaseRequisition/PurchaseRequisitionCreate#!/'
    }).when('/SPRApprovalList', {
        templateUrl: '/Inventory/SPRApproval/SPRApprovalList#!/'
    }).when('/SPR2ndApprovalList', {
        templateUrl: '/Inventory/SPRApproval/SPR2ndApprovalList#!/'
    }).when('/SPR3rdApprovalList', {
        templateUrl: '/Inventory/SPRApproval/SPR3rdApprovalList#!/'
    }).when('/PurchaseOrderList', {
        templateUrl: '/Inventory/PurchaseOrder/PurchaseOrderList#!/'
    }).when('/PurchaseOrderCreate', {
        templateUrl: '/Inventory/PurchaseOrder/PurchaseOrderCreate#!/'
    }).when('/PendingPOrderCreate', {
        templateUrl: '/Inventory/PurchaseOrder/PendingPOrderCreate#!/'
    }).when('/POApprovalList', {
        templateUrl: '/Inventory/POApproval/POApprovalList#!/'
    }).when('/PO2ndApprovalList', {
        templateUrl: '/Inventory/POApproval/PO2ndApprovalList#!/'
    }).when('/MRRList', {
        templateUrl: '/Inventory/MRR/MRRList#!/'
    }).when('/OpeningStock', {
        templateUrl: '/Inventory/OpeningStock/OpeningStock#!/'
    }).when('/MRRCreate', {
        templateUrl: '/Inventory/MRR/MRRCreate#!/'
    }).when('/MRRHeadOfficeList', {
        templateUrl: '/Inventory/MRRHeadOffice/MRRHeadOfficeList#!/'
    }).when('/MRRHeadOfficeCreate', {
        templateUrl: '/Inventory/MRRHeadOffice/MRRHeadOfficeCreate#!/'
    }).when('/MRSList', {
        templateUrl: '/Inventory/MRS/MRSList#!/'
    }).when('/MRSCreate', {
        templateUrl: '/Inventory/MRS/MRSCreate#!/'
    }).when('/QCList', {
        templateUrl: '/Inventory/QC/QCList#!/'
    }).when('/QCCreate', {
        templateUrl: '/Inventory/QC/QCCreate#!/'
    }).when('/CurrentStockList', {
        templateUrl: '/Inventory/CurrentStock/CurrentStockList#!/'
    }).when('/StoreRequisitionCreate', {
        templateUrl: '/Inventory/StoreRequisition/StoreRequisitionCreate#!/'
    }).when('/StoreRequisitionList', {
        templateUrl: '/Inventory/StoreRequisition/StoreRequisitionList#!/'
    }).when('/ScrapReturnList', {
        templateUrl: '/Inventory/ScrapReturn/ScrapReturnList#!/'
    }).when('/ScrapReturnCreate', {
        templateUrl: '/Inventory/ScrapReturn/ScrapReturnCreate#!/'
    }).when('/SRApprovalList', {
        templateUrl: '/Inventory/SRApproval/SRApprovalList#!/'
    }).when('/SR2ndApprovalList', {
        templateUrl: '/Inventory/SRApproval/SR2ndApprovalList#!/'
    }).when('/IssueList', {
        templateUrl: '/Inventory/Issue/IssueList#!/'
    }).when('/IssueCreate', {
        templateUrl: '/Inventory/Issue/IssueCreate#!/'
    }).when('/TransferList', {
        templateUrl: '/Inventory/ItemTransfer/TransferList#!/'
    }).when('/TransferCreate', {
        templateUrl: '/Inventory/ItemTransfer/TransferCreate#!/'
    }).when('/TransferApprovalList', {
        templateUrl: '/Inventory/TransferApproval/TransferApprovalList#!/'
    }).when('/ItemReturnList', {
        templateUrl: '/Inventory/ItemReturn/ItemReturnList#!/'
    }).when('/ItemReturnCreate', {
        templateUrl: '/Inventory/ItemReturn/ItemReturnCreate#!/'
    }).when('/IRApprovalList', {
        templateUrl: '/Inventory/IRApproval/IRApprovalList#!/'
    }).when('/SubCategoryList', {// Settings
        templateUrl: '/Settings/SubCategory/SubCategoryList#!/'
    }).when('/SubCategoryCreate', {
        templateUrl: '/Settings/SubCategory/SubCategoryCreate#!/'
    }).when('/CategoryList', {
        templateUrl: '/Settings/Category/CategoryList#!/'
    }).when('/CategoryCreate', {
        templateUrl: '/Settings/Category/CategoryCreate#!/'
    }).when('/BrandList', {
        templateUrl: '/Settings/Brand/BrandList#!/'
    }).when('/BrandCreate', {
        templateUrl: '/Settings/Brand/BrandCreate#!/'
    }).when('/ColorList', {
        templateUrl: '/Settings/Color/ColorList#!/'
    }).when('/ColorCreate', {
        templateUrl: '/Settings/Color/ColorCreate#!/'
    }).when('/DepartmentList', {
        templateUrl: '/Settings/Department/DepartmentList#!/'
    }).when('/DepartmentCreate', {
        templateUrl: '/Settings/Department/DepartmentCreate#!/'
    }).when('/TypeList', {
        templateUrl: '/Settings/Type/TypeList#!/'
    }).when('/TypeCreate', {
        templateUrl: '/Settings/Type/TypeCreate#!/'
    }).when('/UnitList', {
        templateUrl: '/Settings/Unit/UnitList#!/'
    }).when('/UnitCreate', {
        templateUrl: '/Settings/Unit/UnitCreate#!/'
    }).when('/WarehouseList', {
        templateUrl: '/Settings/Warehouse/WarehouseList#!/'
    }).when('/WarehouseCreate', {
        templateUrl: '/Settings/Warehouse/WarehouseCreate#!/'
    }).when('/StoreList', {
        templateUrl: '/Settings/Store/StoreList#!/'
    }).when('/StoreCreate', {
        templateUrl: '/Settings/Store/StoreCreate#!/'
    }).when('/StoreRackList', {
        templateUrl: '/Settings/StoreRack/StoreRackList#!/'
    }).when('/StoreRackCreate', {
        templateUrl: '/Settings/StoreRack/StoreRackCreate#!/'
    }).when('/StoreBinList', {
        templateUrl: '/Settings/StoreBin/StoreBinList#!/'
    }).when('/StoreBinCreate', {
        templateUrl: '/Settings/StoreBin/StoreBinCreate#!/'
    }).when('/ProductList', {
        templateUrl: '/Settings/Product/ProductList#!/'
    }).when('/UploadProduct', {
        templateUrl: '/Settings/Product/ProductUpload#!/'
    }).when('/ProductCreate', {
        templateUrl: '/Settings/Product/ProductCreate#!/'
    }).when('/SupplierList', {
        templateUrl: '/Settings/Supplier/SupplierList#!/'
    }).when('/SupplierCreate', {
        templateUrl: '/Settings/Supplier/SupplierCreate#!/'
    }).when('/ClothingTypeCreate', {
        templateUrl: '/Settings/Custom/ClothingTypeCreate#!/'
    }).when('/ClothingTypeList', {
        templateUrl: '/Settings/Custom/ClothingTypeList#!/'
    }).when('/DesignTypeList', {
        templateUrl: '/Settings/Design/DesignTypeList#!/'
    }).when('/DesignCreate', {
        templateUrl: '/Settings/Design/DesignCreate#!/'
    }).when('/PocketCreate', {
        templateUrl: '/Settings/Pocket/PocketCreate#!/'
    }).when('/PocketList', {
        templateUrl: '/Settings/Pocket/PocketList#!/'
    }).when('/LiningCreate', {
        templateUrl: '/Settings/Lining/LiningCreate#!/'
    }).when('/LiningList', {
        templateUrl: '/Settings/Lining/LiningList#!/'
    }).when('/ButtonList', {
        templateUrl: '/Settings/Button/ButtonList#!/'
    }).when('/ButtonCreate', {
        templateUrl: '/Settings/Button/ButtonCreate#!/'
    }).when('/LapelCreate', {
        templateUrl: '/Settings/Lapel/LapelCreate#!/'
    }).when('/LapelList', {
        templateUrl: '/Settings/Lapel/LapelList#!/'
    }).when('/BackCreate', {
        templateUrl: '/Settings/Back/BackCreate#!/'
    }).when('/BackList', {
        templateUrl: '/Settings/Back/BackList#!/'
    }).when('/SleeveList', {
        templateUrl: '/Settings/Sleeve/SleeveList#!/'
    }).when('/SleeveCreate', {
        templateUrl: '/Settings/Sleeve/SleeveCreate#!/'
    }).when('/MachineList', {
        templateUrl: '/Settings/Machine/MachineList#!/'
    }).when('/MachineCreate', {
        templateUrl: '/Settings/Machine/MachineCreate#!/'
    }).when('/ModelList', {
        templateUrl: '/Settings/Model/ModelList#!/'
    }).when('/ModelCreate', {
        templateUrl: '/Settings/Model/ModelCreate#!/'
    }).when('/CompanyList', {
        templateUrl: '/Settings/Company/CompanyList#!/'
    }).when('/CreateCompany', {
        templateUrl: '/Settings/Company/CreateCompany#!/'
    }).when('/SRandIssueReport', {
        templateUrl: '/Reports/TechnoReports/SRandIssueReport#!/'
    }).when('/PosCreate/:id', {
        templateUrl: '/Pos/Pos/PosCreate#!/'
    }).when('/Page', { // Security
        templateUrl: '/Page/Page#!/'
    }).when('/AddPage', {
        templateUrl: '/Page/PageCreate#!/'
    }).when('/User', {
        templateUrl: '/User/User#!/'
    }).when('/AddUser', {
        templateUrl: '/User/UserCreate#!/'
    }).when('/EditUser', {
        templateUrl: '/User/EditUser#!/'
    }).when('/UserGroup', {
        templateUrl: '/UserGroup/UserGroup#!/'
    }).when('/CreateUserGroup', {
        templateUrl: '/UserGroup/UserGroupCreate#!/'
    }).when('/EditUserGroup', {
        templateUrl: '/UserGroup/EditUserGroup#!/'
    }).when('/ChangePassword', {
        templateUrl: '/ChangePassword/ChangePassword#!/'
    }).when('/PasswordChangeByAdmin', {
        templateUrl: '/ChangePassword/PasswordChangeByAdmin#!/'
    }).when('/CustomMade', {
        templateUrl: '/POS/CustomerMode/CustomerMode#!/'
    }).when('/LogIn', {
        templateUrl: '/Security/Login#!/'
    }).when('/LogOut', {
        templateUrl: '/Security/LogOff#!/'
    }).otherwise('/', {
        templateUrl: '/Security/Login#!/'
    });

    toastr.options = {
        "closeButton": true,
        "debug": true,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-bottom-right",
        //"positionClass": "toast-top-full-width",
        "preventDuplicates": true,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }


}).config(['KeepaliveProvider', 'IdleProvider', function (KeepaliveProvider, IdleProvider) {
    IdleProvider.idle(600);
    IdleProvider.timeout(1);
    KeepaliveProvider.interval(105);
}]);

// Following code use for ng-idle logout option
var myApp = angular.module('app');
myApp.run(['Idle', function (Idle) {
    Idle.watch();
}]);
