//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PODtls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_PODtls()
        {
            this.INV_MRR_HODtls = new HashSet<INV_MRR_HODtls>();
        }
    
        public int PODtlsID { get; set; }
        public int POID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public int OrderQty { get; set; }
        public Nullable<int> ApprovedQty { get; set; }
        public decimal UnitRate { get; set; }
        public decimal LineTotal { get; set; }
        public int SPRDtlsID { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR_HODtls> INV_MRR_HODtls { get; set; }
        public virtual INV_PO INV_PO { get; set; }
        public virtual INV_Product INV_Product { get; set; }
        public virtual INV_SPRDtls INV_SPRDtls { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
    }
}
