//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_Return()
        {
            this.INV_ReturnDtls = new HashSet<INV_ReturnDtls>();
        }
    
        public int ReturnID { get; set; }
        public string ReturnNO { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int ReturnTypeID { get; set; }
        public string ReturnType { get; set; }
        public Nullable<int> FromWarehouseID { get; set; }
        public Nullable<int> ToWarehouseID { get; set; }
        public Nullable<int> FromStoreID { get; set; }
        public Nullable<int> ToStoreID { get; set; }
        public Nullable<int> ToSupplierID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> SRID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public string Status { get; set; }
    
        public virtual SET_CompanyBranch SET_CompanyBranch { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch1 { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch2 { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ReturnDtls> INV_ReturnDtls { get; set; }
    }
}
