//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Brand
    {
        public int BrandID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public int Status { get; set; }
    
        public virtual SET_Country SET_Country { get; set; }
    }
}
