//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_BinCard
    {
        public int CardID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime TDate { get; set; }
        public string SPRNO { get; set; }
        public string MRRNO { get; set; }
        public string IssueNO { get; set; }
        public int DetailsID { get; set; }
        public string TType { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
        public Nullable<decimal> IssueOut { get; set; }
        public string McRff { get; set; }
    
        public virtual INV_Product INV_Product { get; set; }
    }
}
