//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_SRDtls
    {
        public int SRDtlsID { get; set; }
        public int SRID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public int ReqQty { get; set; }
        public Nullable<int> ApprovedQty { get; set; }
        public Nullable<int> IssueQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        public virtual INV_Product INV_Product { get; set; }
        public virtual INV_SR INV_SR { get; set; }
        public virtual INV_SubCategory INV_SubCategory { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
    }
}
