//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MaterialReceiveDtls
    {
        public int ReceiveDtlsID { get; set; }
        public int MaterialReceiveID { get; set; }
        public int PODtlsID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public decimal ReceiveQty { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        public virtual INV_MaterialReceive INV_MaterialReceive { get; set; }
    }
}
