//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_SPRDtls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_SPRDtls()
        {
            this.INV_PODtls = new HashSet<INV_PODtls>();
        }
    
        public int SPRDtlsID { get; set; }
        public int SPRID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public int ReqQty { get; set; }
        public Nullable<int> ApprovedQty { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PODtls> INV_PODtls { get; set; }
        public virtual INV_Product INV_Product { get; set; }
        public virtual INV_SPR INV_SPR { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
    }
}
