//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_IssueDtls
    {
        public int IssueDtlsID { get; set; }
        public int IssueID { get; set; }
        public int SRDtlsID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public int IssueQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual INV_Category INV_Category { get; set; }
        public virtual INV_Issue INV_Issue { get; set; }
        public virtual INV_Product INV_Product { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
    }
}
