//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_Supplier()
        {
            this.INV_MRR = new HashSet<INV_MRR>();
            this.INV_MRR_HO = new HashSet<INV_MRR_HO>();
            this.INV_PO = new HashSet<INV_PO>();
            this.INV_SupplierProduct = new HashSet<INV_SupplierProduct>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string BankName { get; set; }
        public string BankAcNO { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR> INV_MRR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR_HO> INV_MRR_HO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PO> INV_PO { get; set; }
        public virtual SET_Country SET_Country { get; set; }
        public virtual SET_Currency SET_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SupplierProduct> INV_SupplierProduct { get; set; }
    }
}
