//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_Product()
        {
            this.INV_BinCard = new HashSet<INV_BinCard>();
            this.INV_IssueDtls = new HashSet<INV_IssueDtls>();
            this.INV_MRR_HODtls = new HashSet<INV_MRR_HODtls>();
            this.INV_OpeningStock = new HashSet<INV_OpeningStock>();
            this.INV_PODtls = new HashSet<INV_PODtls>();
            this.INV_ProductBin = new HashSet<INV_ProductBin>();
            this.INV_ProductDepartment = new HashSet<INV_ProductDepartment>();
            this.INV_ProductSize = new HashSet<INV_ProductSize>();
            this.INV_ReturnDtls = new HashSet<INV_ReturnDtls>();
            this.INV_ScrapReturnDtls = new HashSet<INV_ScrapReturnDtls>();
            this.INV_SPRDtls = new HashSet<INV_SPRDtls>();
            this.INV_SRDtls = new HashSet<INV_SRDtls>();
            this.INV_Stock = new HashSet<INV_Stock>();
            this.INV_SupplierProduct = new HashSet<INV_SupplierProduct>();
            this.INV_TransferDtls = new HashSet<INV_TransferDtls>();
        }
    
        public int ProductID { get; set; }
        public int BranchID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public int MachineID { get; set; }
        public int ModelID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string PartNumber { get; set; }
        public Nullable<decimal> ReOrderLevel { get; set; }
        public Nullable<decimal> MinimumLevel { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public int ImportTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string SerialNO { get; set; }
        public string ImageURL { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_BinCard> INV_BinCard { get; set; }
        public virtual INV_Category INV_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_IssueDtls> INV_IssueDtls { get; set; }
        public virtual INV_Machine INV_Machine { get; set; }
        public virtual INV_Model INV_Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR_HODtls> INV_MRR_HODtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_OpeningStock> INV_OpeningStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PODtls> INV_PODtls { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
        public virtual INV_Type INV_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ProductBin> INV_ProductBin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ProductDepartment> INV_ProductDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ProductSize> INV_ProductSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ReturnDtls> INV_ReturnDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ScrapReturnDtls> INV_ScrapReturnDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SPRDtls> INV_SPRDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SRDtls> INV_SRDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_Stock> INV_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SupplierProduct> INV_SupplierProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TransferDtls> INV_TransferDtls { get; set; }
    }
}
