//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ProductBin
    {
        public int ProductBinID { get; set; }
        public int ProductID { get; set; }
        public int StoreBinID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual INV_Product INV_Product { get; set; }
        public virtual INV_StoreBin INV_StoreBin { get; set; }
    }
}
