//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_SPR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_SPR()
        {
            this.INV_MRR = new HashSet<INV_MRR>();
            this.INV_PO = new HashSet<INV_PO>();
            this.INV_SPRDtls = new HashSet<INV_SPRDtls>();
        }
    
        public int SPRID { get; set; }
        public string SPRNO { get; set; }
        public System.DateTime SPRDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public int BranchID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> FirstApproveBy { get; set; }
        public Nullable<System.DateTime> FirstApproveDate { get; set; }
        public string FirstApproveStatus { get; set; }
        public Nullable<int> SecondApproveBy { get; set; }
        public Nullable<System.DateTime> SecondApproveDate { get; set; }
        public string SecondApproveStatus { get; set; }
        public Nullable<int> ThirdApproveBy { get; set; }
        public Nullable<System.DateTime> ThirdApproveDate { get; set; }
        public string ThirdApproveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR> INV_MRR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PO> INV_PO { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch { get; set; }
        public virtual SEC_UserInformation SEC_UserInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_SPRDtls> INV_SPRDtls { get; set; }
    }
}
