//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MaterialReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_MaterialReceive()
        {
            this.INV_MaterialReceiveDtls = new HashSet<INV_MaterialReceiveDtls>();
        }
    
        public int MaterialReceiveID { get; set; }
        public int POID { get; set; }
        public string ReceiveNO { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual SEC_UserInformation SEC_UserInformation { get; set; }
        public virtual INV_PO INV_PO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MaterialReceiveDtls> INV_MaterialReceiveDtls { get; set; }
    }
}
