//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_StoreRack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_StoreRack()
        {
            this.INV_StoreBin = new HashSet<INV_StoreBin>();
        }
    
        public int StoreRackID { get; set; }
        public int BranchID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_StoreBin> INV_StoreBin { get; set; }
        public virtual SET_CompanyBranch SET_CompanyBranch { get; set; }
    }
}
