//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_QCDtls
    {
        public int QCDtlsID { get; set; }
        public int QCID { get; set; }
        public int CategoryID { get; set; }
        public int ProductID { get; set; }
        public int UnitID { get; set; }
        public decimal ReceiveQty { get; set; }
        public decimal QCPassQty { get; set; }
        public decimal QCFailQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual INV_QC INV_QC { get; set; }
    }
}
