//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_PO()
        {
            this.INV_MaterialReceive = new HashSet<INV_MaterialReceive>();
            this.INV_MRR = new HashSet<INV_MRR>();
            this.INV_MRR_HO = new HashSet<INV_MRR_HO>();
            this.INV_PODtls = new HashSet<INV_PODtls>();
        }
    
        public int POID { get; set; }
        public Nullable<int> SPRID { get; set; }
        public string PONO { get; set; }
        public System.DateTime PODate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int SupplierID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> FirstApproveBy { get; set; }
        public Nullable<System.DateTime> FirstApproveDate { get; set; }
        public string FirstApproveStatus { get; set; }
        public Nullable<int> SecondApproveBy { get; set; }
        public Nullable<System.DateTime> SecondApproveDate { get; set; }
        public string SecondApproveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MaterialReceive> INV_MaterialReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR> INV_MRR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_MRR_HO> INV_MRR_HO { get; set; }
        public virtual SEC_UserInformation SEC_UserInformation { get; set; }
        public virtual INV_SPR INV_SPR { get; set; }
        public virtual INV_Supplier INV_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PODtls> INV_PODtls { get; set; }
    }
}
